version: 2
jobs:
  build:

    working_directory: ~/repo

    docker:
      - image: circleci/openjdk:8-jdk-browsers

    environment:
      MAVEN_OPTS: -Xmx3200m
    
    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "pom.xml" }}
          
      - run: curl https://circleci.com/api/v1.1/project/github/javacreed/domain-primitives-api/8/artifacts?circle-token=$CIRCLE_TOKEN | grep -o 'https://[^"]*' > artifacts.txt
      - run: <artifacts.txt xargs -P4 -I % wget %?circle-token=$CIRCLE_TOKEN
      - run: mvn install:install-file -DgroupId=com.javacreed.api -DartifactId=domain-primitives-api -Dversion=1.0.0 -Dpackaging=jar -Dfile=domain-primitives-api-1.0.0.jar

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      - run: mvn package

      - store_test_results:
          path: target/surefire-reports

      - store_artifacts:
          path: target/domain-primitives-api-jpa-1.0.0.jar
